#!/usr/bin/env python3
"""Generate or audit Pre-CU skill-box display data from an SWG skills.tab.

The client-side Pre-CU skills mediator cannot safely consume a server-compiled
skills.iff. It therefore uses a generated C++ header for the commands,
schematics, and skill modifiers displayed in each box. This tool makes that
generation reproducible from an explicit tabular source instead of a
machine-local JavaScript project.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import re
import sys
from dataclasses import dataclass
from pathlib import Path


REQUIRED_COLUMNS = {
    "NAME",
    "COMMANDS",
    "SKILL_MODS",
    "SCHEMATICS_GRANTED",
}

COMMAND_ROW = re.compile(r'^\s*\{\s*"([^"]+)",\s*"([^"]+)"\s*\},\s*$')
MOD_ROW = re.compile(
    r'^\s*\{\s*"([^"]+)",\s*"([^"]+)",\s*(-?\d+)\s*\},\s*$'
)


class SkillDataError(Exception):
    """Raised when a skills table cannot be converted safely."""


@dataclass(frozen=True, order=True)
class CommandGrant:
    skill: str
    command: str


@dataclass(frozen=True, order=True)
class SkillModGrant:
    skill: str
    modifier: str
    value: int


@dataclass(frozen=True)
class SkillBoxData:
    skill_count: int
    commands: tuple[CommandGrant, ...]
    modifiers: tuple[SkillModGrant, ...]


def _split_list(value: str | None) -> list[str]:
    if not value:
        return []
    return [item.strip() for item in value.split(",") if item.strip()]


def load_skill_box_data(path: Path) -> SkillBoxData:
    try:
        stream = path.open("r", encoding="utf-8-sig", newline="")
    except OSError as exc:
        raise SkillDataError(f"unable to open {path}: {exc}") from exc

    commands: set[CommandGrant] = set()
    modifiers: set[SkillModGrant] = set()
    skill_count = 0

    with stream:
        reader = csv.DictReader(stream, delimiter="\t")
        if reader.fieldnames is None:
            raise SkillDataError(f"{path} has no header row")

        missing = REQUIRED_COLUMNS.difference(reader.fieldnames)
        if missing:
            raise SkillDataError(
                f"{path} is missing columns: {', '.join(sorted(missing))}"
            )

        for line_number, row in enumerate(reader, start=2):
            skill = (row.get("NAME") or "").strip()

            # SWG text datatables place a type/default row below the header.
            if line_number == 2 and skill.lower() in {"s", "string"}:
                continue
            if not skill:
                continue

            skill_count += 1
            raw_grants = _split_list(row.get("COMMANDS"))
            raw_grants.extend(_split_list(row.get("SCHEMATICS_GRANTED")))
            for grant in raw_grants:
                if grant == "_" or grant.startswith("private_"):
                    continue
                commands.add(CommandGrant(skill, grant))

            for raw_modifier in _split_list(row.get("SKILL_MODS")):
                if "=" not in raw_modifier:
                    raise SkillDataError(
                        f"{path}:{line_number}: invalid SKILL_MODS entry "
                        f"{raw_modifier!r}"
                    )
                modifier, raw_value = raw_modifier.rsplit("=", 1)
                modifier = modifier.strip()
                if not modifier or modifier.startswith("private_"):
                    continue
                try:
                    value = int(raw_value.strip())
                except ValueError as exc:
                    raise SkillDataError(
                        f"{path}:{line_number}: non-integer modifier "
                        f"{raw_modifier!r}"
                    ) from exc
                modifiers.add(SkillModGrant(skill, modifier, value))

    return SkillBoxData(
        skill_count=skill_count,
        commands=tuple(sorted(commands)),
        modifiers=tuple(sorted(modifiers)),
    )


def _cpp_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def render_header(data: SkillBoxData, source_sha256: str) -> str:
    lines = [
        "// Auto-generated by scripts/generate_precu_skill_box_data.py",
        f"// Source skills.tab SHA-256: {source_sha256}",
        "// Private/internal grants are intentionally excluded. Do not edit by hand.",
        "",
        "struct SkillBoxCommand { char const * skill; char const * command; };",
        "static SkillBoxCommand const k_skillBoxCommands[] = {",
    ]
    for grant in data.commands:
        lines.append(
            f'\t{{ "{_cpp_string(grant.skill)}", '
            f'"{_cpp_string(grant.command)}" }},'
        )
    lines.extend(
        [
            "};",
            "static int const k_skillBoxCommandsCount = "
            "sizeof(k_skillBoxCommands) / sizeof(k_skillBoxCommands[0]); "
            f"// {len(data.commands)}",
            "",
            "struct SkillBoxMod { char const * skill; char const * mod; int value; };",
            "static SkillBoxMod const k_skillBoxMods[] = {",
        ]
    )
    for grant in data.modifiers:
        lines.append(
            f'\t{{ "{_cpp_string(grant.skill)}", '
            f'"{_cpp_string(grant.modifier)}", {grant.value} }},'
        )
    lines.extend(
        [
            "};",
            "static int const k_skillBoxModsCount = "
            "sizeof(k_skillBoxMods) / sizeof(k_skillBoxMods[0]); "
            f"// {len(data.modifiers)}",
            "",
        ]
    )
    return "\n".join(lines)


def parse_existing_header(path: Path) -> SkillBoxData:
    try:
        lines = path.read_text(encoding="utf-8").splitlines()
    except OSError as exc:
        raise SkillDataError(f"unable to read {path}: {exc}") from exc

    commands: set[CommandGrant] = set()
    modifiers: set[SkillModGrant] = set()
    for line in lines:
        command_match = COMMAND_ROW.match(line)
        if command_match:
            commands.add(CommandGrant(*command_match.groups()))
            continue
        modifier_match = MOD_ROW.match(line)
        if modifier_match:
            skill, modifier, value = modifier_match.groups()
            modifiers.add(SkillModGrant(skill, modifier, int(value)))

    return SkillBoxData(
        skill_count=0,
        commands=tuple(sorted(commands)),
        modifiers=tuple(sorted(modifiers)),
    )


def _print_difference(label: str, source: set[object], existing: set[object], limit: int) -> bool:
    missing = sorted(source.difference(existing))
    extra = sorted(existing.difference(source))
    print(
        f"{label}: source={len(source)} existing={len(existing)} "
        f"missing={len(missing)} extra={len(extra)}"
    )
    for value in missing[:limit]:
        print(f"  missing: {value}")
    for value in extra[:limit]:
        print(f"  extra:   {value}")
    return bool(missing or extra)


def audit_header(source: SkillBoxData, existing_path: Path, limit: int) -> bool:
    existing = parse_existing_header(existing_path)
    changed = _print_difference(
        "commands/schematics", set(source.commands), set(existing.commands), limit
    )
    changed |= _print_difference(
        "skill modifiers", set(source.modifiers), set(existing.modifiers), limit
    )
    return changed


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate or audit SwgCuiSkillBoxData.h from a skills.tab"
    )
    parser.add_argument("--skills-tab", required=True, type=Path)
    parser.add_argument("--output", type=Path)
    parser.add_argument("--force", action="store_true")
    parser.add_argument("--audit-header", type=Path)
    parser.add_argument("--strict-audit", action="store_true")
    parser.add_argument("--difference-limit", type=int, default=10)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    try:
        source_bytes = args.skills_tab.read_bytes()
        source_sha256 = hashlib.sha256(source_bytes).hexdigest().upper()
        data = load_skill_box_data(args.skills_tab)
        print(
            f"skills={data.skill_count} commands/schematics={len(data.commands)} "
            f"modifiers={len(data.modifiers)} sha256={source_sha256}"
        )

        if args.output:
            if args.output.exists() and not args.force:
                raise SkillDataError(
                    f"refusing to overwrite {args.output}; pass --force explicitly"
                )
            args.output.parent.mkdir(parents=True, exist_ok=True)
            args.output.write_text(
                render_header(data, source_sha256), encoding="utf-8", newline="\n"
            )
            print(f"wrote {args.output}")

        audit_changed = False
        if args.audit_header:
            audit_changed = audit_header(
                data, args.audit_header, max(0, args.difference_limit)
            )
        if args.strict_audit and audit_changed:
            return 1
        return 0
    except (OSError, SkillDataError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main())
