[CmdletBinding()]
param(
    [string]$ClientRoot = "E:\SWG\SWGSource\SWGSource Client v3.0",

    [string]$OfflineRoot,

    [ValidateRange(1, 14)]
    [int]$InstrumentId = 6,

    [string]$InstrumentTemplate = "object/tangible/instrument/shared_fizz.iff",

    [string]$Terrain = "terrain/tatooine.trn",

    [string]$Avatar = "object/creature/player/shared_human_male.iff",

    [switch]$NoBuild
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$repoRoot = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot "..")).Path
$clientRootPath = (Resolve-Path -LiteralPath $ClientRoot).Path
if (-not $OfflineRoot) {
    $OfflineRoot = Join-Path (Split-Path -Parent $clientRootPath) "Staging\EntertainerOfflineClient"
}
$offlineRootPath = [IO.Path]::GetFullPath($OfflineRoot)
if ($offlineRootPath.TrimEnd("\") -eq $clientRootPath.TrimEnd("\")) {
    throw "OfflineRoot must be separate from ClientRoot."
}

if (-not $NoBuild) {
    & (Join-Path $PSScriptRoot "Build-X64Client.ps1") -Configuration Release
}

New-Item -ItemType Directory -Path $offlineRootPath -Force | Out-Null

# Reuse the large immutable archives without duplicating disk space.
$assetFiles = @(Get-ChildItem -LiteralPath $clientRootPath -File | Where-Object { $_.Extension -in @(".tre", ".toc") })
foreach ($source in $assetFiles) {
    $destination = Join-Path $offlineRootPath $source.Name
    if (-not (Test-Path -LiteralPath $destination)) {
        New-Item -ItemType HardLink -Path $destination -Target $source.FullName | Out-Null
    }
}

$assetDirectories = @("appearance", "clientdata", "customization", "datatables", "misc", "object", "shader", "string", "texture")
foreach ($name in $assetDirectories) {
    $source = Join-Path $clientRootPath $name
    $destination = Join-Path $offlineRootPath $name
    if ((Test-Path -LiteralPath $source -PathType Container) -and -not (Test-Path -LiteralPath $destination)) {
        New-Item -ItemType Junction -Path $destination -Target $source | Out-Null
    }
}

# UI files are patched by Stage-X64Client.ps1, so keep an isolated copy in the
# offline sandbox instead of junctioning back into the gameplay client.
$sourceUi = Join-Path $clientRootPath "ui"
$offlineUi = Join-Path $offlineRootPath "ui"
if ((Test-Path -LiteralPath $sourceUi -PathType Container) -and -not (Test-Path -LiteralPath $offlineUi)) {
    Copy-Item -LiteralPath $sourceUi -Destination $offlineUi -Recurse
}

Get-ChildItem -LiteralPath $clientRootPath -Filter "*.cfg" -File | Copy-Item -Destination $offlineRootPath -Force
$clientConfigPath = Join-Path $offlineRootPath "client.cfg"
$clientConfig = [IO.File]::ReadAllText($clientConfigPath)
if ($clientConfig -notmatch '(?im)^\s*\.include\s+"offline-entertainer\.cfg"\s*$') {
    $clientConfig = $clientConfig.TrimEnd() + [Environment]::NewLine + '.include "offline-entertainer.cfg"' + [Environment]::NewLine
}
$utf8NoBom = [Text.UTF8Encoding]::new($false)
[IO.File]::WriteAllText($clientConfigPath, $clientConfig, $utf8NoBom)

$offlineConfig = @"
# Generated by Start-EntertainerOfflineClient.ps1. This sandbox never connects to a server.
[ClientGame]
    groundScene=$Terrain
    avatarSelection=$Avatar
    singlePlayerStartLocationX=0
    singlePlayerStartLocationY=0
    singlePlayerStartLocationZ=0
    entertainerOfflineInstrumentId=$InstrumentId
    entertainerOfflineInstrumentTemplate=$InstrumentTemplate
    autoConnectToLoginServer=false
    autoConnectToCentralServer=false
    autoConnectToGameServer=false
    skipIntro=true
    skipSplash=true

[SwgClient]
    allowMultipleInstances=true
"@
[IO.File]::WriteAllText((Join-Path $offlineRootPath "offline-entertainer.cfg"), $offlineConfig.TrimStart() + [Environment]::NewLine, $utf8NoBom)

& (Join-Path $PSScriptRoot "Stage-X64Client.ps1") -ClientRoot $offlineRootPath -Configuration Release -NoBackup

$executable = Join-Path $offlineRootPath "SwgClient_r.exe"
$process = Start-Process -FilePath $executable -WorkingDirectory $offlineRootPath -WindowStyle Normal -PassThru
Write-Host "Offline entertainer client started (PID $($process.Id))."
Write-Host "In chat, run /startMidiToMusic. Press Escape to leave performance mode."
Write-Host "Instrument $InstrumentId ($InstrumentTemplate); sandbox: $offlineRootPath"
